# Generated by Django 4.2.28 on 2026-02-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senti_app', '0003_sentimentanalysis_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
